<?php

namespace App\Services;

use App\Models\Rental;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class AirtableService
{
    protected $baseId;
    protected $token;
    protected $table;
    protected $logger;

    public function __construct()
    {
        $this->baseId = config('services.airtable.base_id');
        $this->token = config('services.airtable.token');
        $this->table = config('services.airtable.table');
    }

    /**
     * Map rental data to Airtable fields and sync.
     *
     * @param Rental $rental
     * @return void
     */
    public function updateOrInsertRental(Rental $rental)
    {
        try {
            $rental->loadMissing('tournament.sport');

            $fields = [
                'Customer Name' => $rental->full_name ?? 'N/A',
                'Customer Email Address' => $rental->email ?? 'N/A',
                'Customer Phone Number' => $rental->phone_number ?? 'N/A',
                'Order Date' => $rental->created_at ? $rental->created_at->format('Y-m-d H:i:s') : now()->format('Y-m-d H:i:s'),
                'Complex' => optional($rental->tournament)->location ?? 'N/A',
                'Tournament Name' => optional($rental->tournament)->name ?? 'N/A',
                'Order Total' => (float) ($rental->total_amount ?? 0),
                'Order Status' => $rental->status ?? 'pending',
                'Delivery Method' => $rental->booking_source ?? 'website',
                // 'Flat Fee (Look Up)' is a lookup field, we don't send data to it directly
                'Tournament Tracker' => (string) ($rental->tournament_id ?? ''),
                'Tax Amount' => (float) ($rental->tax_amount ?? 0),
                'Items + Quantities' => $this->formatItemsAndBundles($rental),
                // 'Last Modified' is auto-generated by Airtable
                'Payment Status' => $rental->payment_status ?? 'pending',
                // 'Tournament Start Date' is a lookup field
            ];

            $this->log("Syncing rental #{$rental->id} to Airtable", $fields);

            $existingRecordId = $rental->airtable_id;

            // 1. If we don't have an ID, try to search for one (fallback for existing records)
            if (!$existingRecordId) {
                $email = $rental->email;
                $formattedDate = $rental->created_at ? $rental->created_at->format('Y-m-d H:i') : null;

                if ($email && $formattedDate) {
                    $filter = "AND({Customer Email Address} = '{$email}', DATETIME_FORMAT({Order Date}, 'YYYY-MM-DD HH:mm') = '{$formattedDate}')";

                    $searchResponse = Http::withToken($this->token)
                        ->get("https://api.airtable.com/v0/{$this->baseId}/" . urlencode($this->table), [
                            'filterByFormula' => $filter
                        ]);

                    if ($searchResponse->successful() && !empty($searchResponse->json()['records'])) {
                        $existingRecordId = $searchResponse->json()['records'][0]['id'];
                        $this->log("Found existing record ID via search: {$existingRecordId} for rental #{$rental->id}");

                        // Save the ID to the rental for future use
                        $rental->update(['airtable_id' => $existingRecordId]);
                    }
                }
            }

            if ($existingRecordId) {
                // PATCH (Update existing)
                $response = Http::withToken($this->token)
                    ->patch("https://api.airtable.com/v0/{$this->baseId}/" . urlencode($this->table) . "/{$existingRecordId}", [
                        'fields' => $fields,
                        'typecast' => true
                    ]);

                // If PATCH fails because record was deleted, we might want to try POST, 
                // but let's keep it simple for now as per user request.
            } else {
                // POST (Create new)
                $response = Http::withToken($this->token)
                    ->post("https://api.airtable.com/v0/{$this->baseId}/" . urlencode($this->table), [
                        'fields' => $fields,
                        'typecast' => true
                    ]);

                if ($response->successful()) {
                    $newId = $response->json()['id'];
                    $this->log("Created new Airtable record with ID: {$newId} for rental #{$rental->id}");
                    $rental->update(['airtable_id' => $newId]);
                }
            }


            if ($response->successful()) {
                $this->log("Successfully synced rental #{$rental->id} to Airtable", $response->json());
            } else {
                $this->log("Failed to sync rental #{$rental->id} to Airtable", $response->json(), 'error');
            }
        } catch (\Throwable $e) {
            $this->log("Critical error syncing rental #{$rental->id} to Airtable: " . $e->getMessage(), [], 'error');
        }
    }

    /**
     * Format items and bundles for Airtable.
     *
     * @param Rental $rental
     * @return string
     */
    protected function formatItemsAndBundles(Rental $rental)
    {
        $items = [];
        if (is_array($rental->items)) {
            foreach ($rental->items as $item) {
                $itemModel = \App\Models\Item::find($item['item_id']);
                $name = $itemModel ? $itemModel->name : "Item #{$item['item_id']}";
                $items[] = "{$name} (x{$item['quantity']})";
            }
        }

        if (is_array($rental->bundles)) {
            foreach ($rental->bundles as $bundle) {
                $bundleId = is_array($bundle) ? ($bundle['bundle_id'] ?? null) : $bundle;
                $quantity = is_array($bundle) ? ($bundle['quantity'] ?? 1) : 1;
                $bundleModel = \App\Models\Bundle::find($bundleId);
                $name = $bundleModel ? $bundleModel->name : "Bundle #{$bundleId}";
                $items[] = "{$name} (x{$quantity})";
            }
        }

        return implode(', ', $items);
    }

    /**
     * Separate logging for Airtable.
     *
     * @param string $message
     * @param array $data
     * @param string $level
     * @return void
     */
    public function log($message, $data = [], $level = 'info')
    {
        $logMessage = "[" . now() . "] {$level}: {$message} " . json_encode($data);
        Log::build([
                    'driver' => 'single',
                    'path' => storage_path('logs/airtable.log'),
                ])->{$level}($logMessage);
    }
}
